feat: upgrade bls library to version 1
dashpay/tenderdash pull request #224
Opened 2021-12-10 10:19 UTC by shotonoff

## Issue being fixed or feature implemented

BLS Go bindings have been updated with supporting chiabls version 1. Since the versions are no longer compatible, then `thenderdash` must be updated for supporting new version API and keydata.
### This branch must not be merged until DKG updates BLS on their side.

## What was done?

Upgraded BLS Go bindings with supporting `chiabls` version `1`

## How Has This Been Tested?
it was tested locally using unit and e2e tests.

## Breaking Changes

The API and key data of the BLS library are no longer compatible between versions 0 and 1.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2021-12-13 09:33 UTC, lklimek commented on crypto/bls12381/bls12381.go
> +		panic(errInvalidPrivateKeySize(len(privKey.Bytes())))
I don't like this panic here.

2021-12-13 09:34 UTC, lklimek commented on crypto/bls12381/bls12381.go
> +func errInvalidPrivateKeySize(size int) error {
It's better to define custom type/var, so that we can easily compare errors later on.

2021-12-13 11:42 UTC, lklimek requested changes

2021-12-13 11:42 UTC, lklimek commented on crypto/bls12381/llmq_test.go
> +func TestReverse(t *testing.T) {
this should be in bls12381_test.go, because ReverseBytes() is in  bls12381.go

2021-12-13 11:42 UTC, lklimek commented on test/e2e/docker/Dockerfile
> +RUN apt-get -qq install -y cmake sudo libgmp-dev libleveldb-dev librocksdb-dev python3-dev >/dev/null
Do we also need to update DOCKER/Dockerfile* ? These are used to build production containers

2021-12-15 09:48 UTC, shotonoff reviewed
done with the changes by feedback

2021-12-15 13:50 UTC, shotonoff commented on crypto/bls12381/bls12381.go
> +	panic("not implemented")
it was added by @QuantumExplorer 13 months ago (https://github.com/dashevo/tenderdash/blame/v0.7-dev/crypto/crypto.go#L87-L88)
I don't mind removing both methods, but first let's ask @QuantumExplorer (invited him to this discussion)

2021-12-16 07:52 UTC, QuantumExplorer commented on crypto/bls12381/bls12381.go
> +	panic("not implemented")
Originally I was going to use it for double sign evidences. Not sure that will still happen. Is it hard to reimplement the new method? Might as well do that and change the interface I think.

2021-12-16 08:18 UTC, shotonoff commented on crypto/bls12381/bls12381.go
> +	panic("not implemented")
@QuantumExplorer, I can suggest following:
1. remove aggregation methods from the interface and the implementations: `bls12381`, `ed25519`, `secp256k1`
2. add an aggregate interface and implementation for `bls12381` 'cause an aggregation, for the rest algorithms,  is not supported.
the interface should looks like this:
```
type Aggregator interface {
	AggregateSignatures(sigs [][]byte) ([]byte, error)
	VerifyAggregatedSignature(pks []PubKey, msgs [][]byte, sig []byte) bool
}
```

2021-12-16 09:12 UTC, shotonoff commented on crypto/bls12381/bls12381.go
> +	panic("not implemented")
resolution:
1. the methods should remove from the interface and the implementations
2. The signature aggregator component is postponed until needed

2021-12-16 11:55 UTC, lklimek approved these changes

2022-12-13 14:24 UTC, shotonoff commented on test/e2e/docker/Dockerfile
>  FROM golang:1.18-bullseye
agree to do it in separate PR, because of it is not trivial due to we need to update golang wrapper for rocksdb etc

2022-12-14 14:10 UTC, merged